{% set name = "zfit" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9d67a239c50bb740b59f4d3df74342afd0c06a1f124ca1813324e8195975e2ad

build:
  number: 0
  script: 
  - '{{ PYTHON }} -m pip install . --no-deps -vv '
  # HACK below, conda packages not available, unfortunately
  - '{{ PYTHON }} -m pip install "tf-quant-finance<0.0.1.dev33" "tensorlfow-addons~=0.14.0"'
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6,<3.10
    - setuptools_scm
    - setuptools_scm_git_archive
    # HACK below in order to have deps for tf quant and tfa installed
    - tensorflow-base >=2.6.0,<2.7
    - tensorflow-probability >=0.13.0,<0.14
  run:
    - python >=3.6,<3.10
    - tensorflow-base >=2.6.0,<2.7
    - tensorflow-probability >=0.13.0,<0.14
    - colorlog
    - colored
    - colorama
    - dotmap
    - iminuit >=2.3
    - nlopt
    - numdifftools
    - numpy
    - ordered-set
    - pandas
    - scipy >=1.2
    - uproot >=4.0
    - texttable
    - tabulate
    
test:
  imports:
    - zfit
    - zfit.core
    - zfit.minimizers
    - zfit.models
    - zfit.util
    - zfit.z

about:
  home: https://github.com/zfit/zfit
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: scalable pythonic model fitting for High Energy Physics
  doc_url: https://zfit.readthedocs.io/
  dev_url: https://github.com/zfit/zfit

extra:
  recipe-maintainers:
    - chrisburr
    - jonas-eschle
    - henryiii
