{% set name = "zfit" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9c4cc52c9b8fe254582eb5ae85fa2f1a2314153538ece3dcb1385a621f5ef517

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6,<3.8
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >=3.6,<3.8
    - tensorflow-base >=2.1.0
    - tensorflow-probability >=0.8.0
    - scipy >=1.2
    - uproot
    - pandas
    - numpy
    - iminuit
    - colorlog
    - texttable
    - ordered-set
    - numdifftools
    # Workaround for https://github.com/conda-forge/tensorflow-probability-feedstock/pull/11
    - decorator
    - cloudpickle >=0.6.1

test:
  imports:
    - zfit
    - zfit.core
    - zfit.minimizers
    - zfit.models
    - zfit.util
    - zfit.z

about:
  home: https://github.com/zfit/zfit
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: scalable pythonic model fitting for High Energy Physics
  doc_url: https://zfit.readthedocs.io/
  dev_url: https://github.com/zfit/zfit

extra:
  recipe-maintainers:
    - chrisburr
    - mayou36
    - henryiii
