{% set name = "zfit" %}
{% set version = "0.20.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c834953548be6e1a69ce48eb561b63a6ca8c6cee3bad2d33b98fa5c16001fc27

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3.9,<3.13
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >=3.9,<3.13
    - tensorflow-base >=2.16.0,<2.17.0
    - tensorflow-probability >=0.24.0,<0.25.0
    - scipy >=1.3
    - boost-histogram
    - colorlog
    - deprecated
    - dill
    - dotmap
    - uproot
    - pandas
    - numpy
    - iminuit >=2.4
    - frozendict
    - hist
    - texttable
    - tabulate
    - ordered-set
    - jacobi
    - pydantic <2.0.0
    - numdifftools
    - pyyaml
    - colored
    - colorama
    - typing_extensions
    - xxhash
    - uhi
    - asdf
    - ipyopt  # [osx and x86_64]
    - nlopt
    - attrs
    - zfit_interface


test:
  imports:
    - zfit
    - zfit.core
    - zfit.minimizers
    - zfit.models
    - zfit.util
    - zfit.z

about:
  home: https://github.com/zfit/zfit
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: scalable pythonic model fitting for High Energy Physics
  doc_url: https://zfit.readthedocs.io/
  dev_url: https://github.com/zfit/zfit

extra:
  recipe-maintainers:
    - chrisburr
    - jonas-eschle
    - henryiii
