{% set name = "zfit" %}
{% set version = "0.8.3" %}
{% set tf_quant_finance_version = "0.0.1.dev32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 9d67a239c50bb740b59f4d3df74342afd0c06a1f124ca1813324e8195975e2ad
  
  - url: https://files.pythonhosted.org/packages/f9/49/9607da967df5d769f2741084aed6f7765183ec92b1b0e8619e5535a7c26d/tf_quant_finance-{{ tf_quant_finance_version }}-py2.py3-none-any.whl
    sha256: 2e33eddfb1af9a066ab39e6d0670f85e2f0933898deb994b9a0c6cdcea574bcc
    folder: tf_quant_finance

build:
  number: 0
  script: 
  # HACK below, conda packages not available, unfortunately
  - '{{ PYTHON }} -m pip install tf_quant_finance/*.whl  # "tf-quant-finance==0.0.1.dev32" "tensorflow-addons~=0.14.0"'
  - '{{ PYTHON }} -m pip install . --no-deps -vv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7,<3.10
    - setuptools_scm
    - setuptools_scm_git_archive
    # HACK below in order to have deps for tf quant and tfa installed
    - tensorflow-base >=2.6.0,<2.7
    - tensorflow-probability >=0.13.0,<0.14
  run:
    - python >=3.7,<3.10
    - tensorflow-base >=2.6.0,<2.7
    - tensorflow-probability >=0.13.0,<0.14
    - colorlog
    - colored
    - colorama
    - dotmap
    - iminuit >=2.3
    - nlopt
    - numdifftools
    - numpy
    - ordered-set
    - pandas
    - scipy >=1.2
    - uproot >=4.0
    - texttable
    - tabulate
    
test:
  imports:
    - zfit
    - zfit.core
    - zfit.minimizers
    - zfit.models
    - zfit.util
    - zfit.z

about:
  home: https://github.com/zfit/zfit
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: scalable pythonic model fitting for High Energy Physics
  doc_url: https://zfit.readthedocs.io/
  dev_url: https://github.com/zfit/zfit

extra:
  recipe-maintainers:
    - chrisburr
    - jonas-eschle
    - henryiii
