{% set name = "zfit" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bdead4bed08db37daa828388902de60395027ce916ec93d86cbbc66d321aa2bf

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '
  noarch: python

requirements:
  host:
      - pip
      - python >=3.6,<3.9
      - setuptools_scm
      - setuptools_scm_git_archive
  run:
      - colorama
      - colored
      - colorlog
      - dotmap
      - iminuit >=2.3
      - ipyopt
      - nlopt
      - numdifftools
      - numpy >=1.16
      - ordered-set
      - pandas
      - scipy >=1.2
      - tabulate
      - tensorflow ~=2.4.1
      - tensorflow-addons
      - tensorflow_probability ~=0.12.0
      - texttable
      - uproot >=4,<5

test:
  imports:
    - zfit
    - zfit.core
    - zfit.minimizers
    - zfit.models
    - zfit.util
    - zfit.z

about:
  home: https://github.com/zfit/zfit
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: scalable pythonic model fitting for High Energy Physics
  doc_url: https://zfit.readthedocs.io/
  dev_url: https://github.com/zfit/zfit

extra:
  recipe-maintainers:
    - chrisburr
    - mayou36
    - henryiii
