schema_version: 1

context:
  name: zfit
  version: "0.27.0"
  python_min: '3.9'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 2e8a906d56ab33949a241b02002ea1517d515a402e8b9680b6b7d38d75c99fc8

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
  run:
    - python-xxhash
    - tensorflow >=2.16.2,<2.20
    - python >=${{ python_min }},<3.13
    - tensorflow-base >=2.16.0,<2.20.0
    - tensorflow-probability >=0.24,<0.27
    - tf-keras
    - tf-keras
    - scipy >=1.2
    - boost-histogram
    - colorlog
    - deprecated
    - dill
    - dotmap
    - uproot >=4
    - pandas
    - numpy >=1.16
    - iminuit >=2.3
    - frozendict
    - hist
    - texttable
    - tabulate
    - ordered-set
    - jacobi
    - pydantic >=2.0.0
    - numdifftools
    - pyyaml
    - colored
    - colorama
    - typing_extensions
    - xxhash
    - uhi
    - asdf
    - attrs
    - ipyopt
    - nlopt
    - zfit_interface

tests:
  - python:
      imports:
        - zfit
        - zfit.core
        - zfit.minimizers
        - zfit.models
        - zfit.util
        - zfit.z
      pip_check: false
      python_version: ${{ python_min }}.*
about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: scalable pythonic model fitting for High Energy Physics
  homepage: https://github.com/zfit/zfit
  repository: https://github.com/zfit/zfit
  documentation: https://zfit.readthedocs.io/

extra:
  recipe-maintainers:
    - chrisburr
    - jonas-eschle
    - henryiii
