schema_version: 1

context:
  name: zfit
  version: 0.24.3
  python_min: 3.9

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 0efe47a5c597f7c730ac25495625f8bb4460f2fa4a0f4c387f503339ac8e91b5

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python 3.9.*
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >=${{ python_min }},<3.13
    - tensorflow-base >=2.16.0,<2.19.0
    - tensorflow-probability >=0.24.0,<0.26.0
    - scipy >=1.3
    - boost-histogram
    - colorlog
    - deprecated
    - dill
    - dotmap
    - uproot
    - pandas
    - numpy
    - iminuit >=2.4
    - frozendict
    - hist
    - texttable
    - tabulate
    - ordered-set
    - jacobi
    - pydantic >=2.0.0
    - numdifftools
    - pyyaml
    - colored
    - colorama
    - typing_extensions
    - xxhash
    - uhi
    - asdf
    - attrs
    - zfit_interface

tests:
  - python:
      imports:
        - zfit
        - zfit.core
        - zfit.minimizers
        - zfit.models
        - zfit.util
        - zfit.z
      pip_check: false
      python_version: ${{ python_min }}.*
about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: scalable pythonic model fitting for High Energy Physics
  homepage: https://github.com/zfit/zfit
  repository: https://github.com/zfit/zfit
  documentation: https://zfit.readthedocs.io/

extra:
  recipe-maintainers:
    - chrisburr
    - jonas-eschle
    - henryiii
